version: '3.8'
services:
  app:
    build: .
    container_name: network_guardian_app
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped 